stages:
- name: deploy
  if: tag IS present
language: python
python:
- '2.7'
- '3.6'
jobs:
  include:
  - stage: deploy
    python: '3.6'
    install: skip
    script: skip
    before_script: npm install && npm run build
    deploy:
      stage: deploy
      skip_cleanup: true
      provider: pypi
      on:
        tags: true
      distributions: sdist bdist_wheel
      user: IamShobe
      password:
        secure: DSAHzzb2oBFPGg8G+EONNdYJVC8yYB+OZWsD80xlri3e6iYm8LDD8+LYsS+PJcpfzbAJpN7OW1fE2zY6iROBg6qyU9U+M/kbsfRU3GYBATkeDmmiX5kMLVr1RE5VTOVvmozitaPJa7AzJspbS+jhCkAqwOF64A8u/X9XXuKVDp3ga84wEKgz5Tc8Q8tdbWLALFjTfFQNWRpbaNI8U2KCIJw17mEAtxKvl/yccttP2jbQITFHDVwc0kuyoqiCFEbz5YFDjgfd8nEXSL4+6cyyZc6yUm4NNA3Qqw8vgUJT6IEDh27BIXI9m7xu3aSBtOShEiBOKhQeCdQqnDhB52m/RzqFHDSpRJydfdnhSw9+bMZ0j4f9iKGwR0lNTNG5PYwDM1mOIKfjN0qIc/U9sKCSvUk8WI9o3avoTsi5SL59jA/uqI8PyfROT9X9j0QjF5ZFR3dB1XuHa6HsqiJBGjDL316TMfnNojiVL3xWvc4nZ8VajBJyxnMsxVOC+U0QSUaoJV89YQzbxCSQNWSwXhVMSH3IFeB7LsL3e3dc5sVFVPI7RK9vTRrbM6Mp8KH/sEK8j4X7I7EJvD8GxcJiJiYtNgAAa17btRPpcAjpmRuFCnXbHl/9yC7qCX5d2Z/M9UaqnM2lRAcnmxPmnirLOd3IN7yzY1mIDoLeYTcbD4aCkuI=
